redisio:
  restart: always
  image: redis:latest
postgresql:
  restart: always
  image: postgres:latest
multistreamer:
  restart: always
  image: jprjr/multistreamer:11.0.7-1-amd64  # override with 11.0.7-1-armv6 if needed
  links:
   - redisio
   - postgresql

